create table People (
	id INT,
	first_name VARCHAR(50),
	country VARCHAR(50),
	gender VARCHAR(50),
	age INT,
	money INT
);
insert into People (id, first_name, country, gender, age, money) values (1, 'Kiele', 'Indonesia', 'Female', 17, 64220);
insert into People (id, first_name, country, gender, age, money) values (2, 'Laura', 'China', 'Female', 11, 8540);
insert into People (id, first_name, country, gender, age, money) values (3, 'Chevalier', 'Christmas Island', 'Male', 93, 55028);
insert into People (id, first_name, country, gender, age, money) values (4, 'Rudyard', 'Colombia', 'Male', 58, 77944);
insert into People (id, first_name, country, gender, age, money) values (5, 'Tana', 'Portugal', 'Female', 6, 95493);
insert into People (id, first_name, country, gender, age, money) values (6, 'Reinwald', 'Russia', 'Male', 36, 5253);
insert into People (id, first_name, country, gender, age, money) values (7, 'Quintina', 'Russia', 'Female', 76, 1964);
insert into People (id, first_name, country, gender, age, money) values (8, 'Rianon', 'China', 'Female', 28, 24221);
insert into People (id, first_name, country, gender, age, money) values (9, 'Alfons', 'China', 'Male', 58, 88954);
insert into People (id, first_name, country, gender, age, money) values (10, 'Malinde', 'France', 'Female', 77, 94204);
insert into People (id, first_name, country, gender, age, money) values (11, 'Tab', 'Croatia', 'Male', 20, 72698);
insert into People (id, first_name, country, gender, age, money) values (12, 'Gwendolen', 'Indonesia', 'Female', 9, 62893);
insert into People (id, first_name, country, gender, age, money) values (13, 'Shanda', 'Russia', 'Agender', 35, 96804);
insert into People (id, first_name, country, gender, age, money) values (14, 'Wood', 'China', 'Male', 77, 14920);
insert into People (id, first_name, country, gender, age, money) values (15, 'Zak', 'Portugal', 'Male', 67, 32877);
insert into People (id, first_name, country, gender, age, money) values (16, 'Des', 'Uganda', 'Male', 53, 37170);
insert into People (id, first_name, country, gender, age, money) values (17, 'Ryun', 'France', 'Male', 87, 51703);
insert into People (id, first_name, country, gender, age, money) values (18, 'Perice', 'Portugal', 'Male', 21, 42536);
insert into People (id, first_name, country, gender, age, money) values (19, 'Jany', 'Philippines', 'Female', 42, 23864);
insert into People (id, first_name, country, gender, age, money) values (20, 'Vivyan', 'Greece', 'Female', 94, 42654);
insert into People (id, first_name, country, gender, age, money) values (21, 'Brook', 'China', 'Female', 40, 92678);
insert into People (id, first_name, country, gender, age, money) values (22, 'Erick', 'France', 'Male', 45, 83403);
insert into People (id, first_name, country, gender, age, money) values (23, 'Hernando', 'Colombia', 'Male', 13, 38100);
insert into People (id, first_name, country, gender, age, money) values (24, 'Aurlie', 'China', 'Female', 98, 78111);
insert into People (id, first_name, country, gender, age, money) values (25, 'Jules', 'Indonesia', 'Male', 45, 31535);
insert into People (id, first_name, country, gender, age, money) values (26, 'Fern', 'Bulgaria', 'Female', 47, 25156);
insert into People (id, first_name, country, gender, age, money) values (27, 'Hoebart', 'Cameroon', 'Male', 66, 64305);
insert into People (id, first_name, country, gender, age, money) values (28, 'Kane', 'China', 'Male', 75, 31592);
insert into People (id, first_name, country, gender, age, money) values (29, 'Barbara', 'Serbia', 'Female', 92, 40564);
insert into People (id, first_name, country, gender, age, money) values (30, 'Kennett', 'Sweden', 'Male', 36, 19789);
insert into People (id, first_name, country, gender, age, money) values (31, 'Juana', 'Poland', 'Female', 87, 55598);
insert into People (id, first_name, country, gender, age, money) values (32, 'Jere', 'Venezuela', 'Male', 57, 70402);
insert into People (id, first_name, country, gender, age, money) values (33, 'Isabelle', 'Ghana', 'Female', 19, 54822);
insert into People (id, first_name, country, gender, age, money) values (34, 'Netta', 'Sweden', 'Female', 56, 6240);
insert into People (id, first_name, country, gender, age, money) values (35, 'Desiree', 'France', 'Genderqueer', 60, 32);
insert into People (id, first_name, country, gender, age, money) values (36, 'Eleanor', 'Brazil', 'Female', 52, 96011);
insert into People (id, first_name, country, gender, age, money) values (37, 'Cam', 'China', 'Female', 64, 28188);
insert into People (id, first_name, country, gender, age, money) values (38, 'Ardelis', 'Colombia', 'Female', 95, 69090);
insert into People (id, first_name, country, gender, age, money) values (39, 'Florida', 'South Africa', 'Female', 33, 43581);
insert into People (id, first_name, country, gender, age, money) values (40, 'Darryl', 'Ethiopia', 'Female', 31, 54513);
insert into People (id, first_name, country, gender, age, money) values (41, 'Rosalinda', 'Philippines', 'Agender', 27, 24908);
insert into People (id, first_name, country, gender, age, money) values (42, 'Archie', 'Peru', 'Male', 93, 5188);
insert into People (id, first_name, country, gender, age, money) values (43, 'Marti', 'Guatemala', 'Genderfluid', 50, 62819);
insert into People (id, first_name, country, gender, age, money) values (44, 'Iseabal', 'Finland', 'Female', 91, 16797);
insert into People (id, first_name, country, gender, age, money) values (45, 'Olympia', 'Russia', 'Female', 13, 23523);
insert into People (id, first_name, country, gender, age, money) values (46, 'Minerva', 'Mexico', 'Female', 39, 27245);
insert into People (id, first_name, country, gender, age, money) values (47, 'Gianna', 'Jordan', 'Female', 70, 95049);
insert into People (id, first_name, country, gender, age, money) values (48, 'Vickie', 'Poland', 'Female', 6, 8189);
insert into People (id, first_name, country, gender, age, money) values (49, 'Marris', 'Latvia', 'Female', 30, 35965);
insert into People (id, first_name, country, gender, age, money) values (50, 'Katrine', 'China', 'Female', 84, 56697);
insert into People (id, first_name, country, gender, age, money) values (51, 'Woodman', 'Philippines', 'Male', 52, 91188);
insert into People (id, first_name, country, gender, age, money) values (52, 'Gawen', 'South Africa', 'Male', 26, 74194);
insert into People (id, first_name, country, gender, age, money) values (53, 'Derrick', 'Brazil', 'Male', 94, 67383);
insert into People (id, first_name, country, gender, age, money) values (54, 'Kristofor', 'Philippines', 'Male', 87, 35552);
insert into People (id, first_name, country, gender, age, money) values (55, 'Jethro', 'Rwanda', 'Male', 72, 24025);
insert into People (id, first_name, country, gender, age, money) values (56, 'Dorian', 'United States', 'Female', 89, 61463);
insert into People (id, first_name, country, gender, age, money) values (57, 'Lutero', 'Sweden', 'Male', 63, 40685);
insert into People (id, first_name, country, gender, age, money) values (58, 'Charlotte', 'Tanzania', 'Female', 9, 72402);
insert into People (id, first_name, country, gender, age, money) values (59, 'Phil', 'Chile', 'Genderfluid', 51, 43261);
insert into People (id, first_name, country, gender, age, money) values (60, 'Dorey', 'Portugal', 'Female', 17, 68163);
insert into People (id, first_name, country, gender, age, money) values (61, 'Fran', 'Bulgaria', 'Female', 81, 43493);
insert into People (id, first_name, country, gender, age, money) values (62, 'Rip', 'China', 'Male', 22, 23444);
insert into People (id, first_name, country, gender, age, money) values (63, 'Tammara', 'China', 'Female', 70, 75355);
insert into People (id, first_name, country, gender, age, money) values (64, 'Rahal', 'Indonesia', 'Female', 45, 8609);
insert into People (id, first_name, country, gender, age, money) values (65, 'Kellina', 'Thailand', 'Female', 77, 24596);
insert into People (id, first_name, country, gender, age, money) values (66, 'Griffin', 'Brazil', 'Male', 18, 6422);
insert into People (id, first_name, country, gender, age, money) values (67, 'Stefania', 'Russia', 'Female', 44, 79866);
insert into People (id, first_name, country, gender, age, money) values (68, 'Walden', 'Czech Republic', 'Male', 66, 94003);
insert into People (id, first_name, country, gender, age, money) values (69, 'Diahann', 'China', 'Genderqueer', 84, 54023);
insert into People (id, first_name, country, gender, age, money) values (70, 'Patricio', 'Tanzania', 'Male', 37, 7105);
insert into People (id, first_name, country, gender, age, money) values (71, 'Skippie', 'Slovenia', 'Male', 76, 2812);
insert into People (id, first_name, country, gender, age, money) values (72, 'Wallie', 'South Africa', 'Male', 15, 12966);
insert into People (id, first_name, country, gender, age, money) values (73, 'Rudie', 'Indonesia', 'Male', 100, 6859);
insert into People (id, first_name, country, gender, age, money) values (74, 'Bendix', 'Russia', 'Male', 63, 90925);
insert into People (id, first_name, country, gender, age, money) values (75, 'Fayina', 'Kazakhstan', 'Female', 68, 36647);
insert into People (id, first_name, country, gender, age, money) values (76, 'Quent', 'Czech Republic', 'Male', 91, 31392);
insert into People (id, first_name, country, gender, age, money) values (77, 'Gerald', 'Philippines', 'Male', 26, 62275);
insert into People (id, first_name, country, gender, age, money) values (78, 'Kenton', 'Nigeria', 'Male', 72, 46470);
insert into People (id, first_name, country, gender, age, money) values (79, 'Selinda', 'Ukraine', 'Female', 90, 61227);
insert into People (id, first_name, country, gender, age, money) values (80, 'Dorothee', 'United Kingdom', 'Female', 45, 24399);
insert into People (id, first_name, country, gender, age, money) values (81, 'Fletcher', 'Portugal', 'Male', 69, 36636);
insert into People (id, first_name, country, gender, age, money) values (82, 'Larisa', 'Indonesia', 'Female', 55, 96538);
insert into People (id, first_name, country, gender, age, money) values (83, 'Tatiania', 'Philippines', 'Female', 44, 24248);
insert into People (id, first_name, country, gender, age, money) values (84, 'Toma', 'Russia', 'Female', 16, 95588);
insert into People (id, first_name, country, gender, age, money) values (85, 'Siusan', 'China', 'Polygender', 21, 28302);
insert into People (id, first_name, country, gender, age, money) values (86, 'Kellby', 'Poland', 'Male', 8, 39841);
insert into People (id, first_name, country, gender, age, money) values (87, 'Melany', 'Colombia', 'Female', 14, 48381);
insert into People (id, first_name, country, gender, age, money) values (88, 'Holt', 'Brazil', 'Male', 74, 21206);
insert into People (id, first_name, country, gender, age, money) values (89, 'Preston', 'Tanzania', 'Male', 79, 56411);
insert into People (id, first_name, country, gender, age, money) values (90, 'Hildy', 'Tajikistan', 'Female', 50, 88647);
insert into People (id, first_name, country, gender, age, money) values (91, 'Basile', 'Indonesia', 'Male', 37, 21603);
insert into People (id, first_name, country, gender, age, money) values (92, 'Beauregard', 'China', 'Male', 36, 83135);
insert into People (id, first_name, country, gender, age, money) values (93, 'Laryssa', 'Russia', 'Female', 97, 57058);
insert into People (id, first_name, country, gender, age, money) values (94, 'Mersey', 'Armenia', 'Non-binary', 89, 36030);
insert into People (id, first_name, country, gender, age, money) values (95, 'Ginelle', 'Saint Lucia', 'Female', 37, 36107);
insert into People (id, first_name, country, gender, age, money) values (96, 'Herb', 'China', 'Male', 49, 76071);
insert into People (id, first_name, country, gender, age, money) values (97, 'Shermie', 'Poland', 'Male', 57, 88115);
insert into People (id, first_name, country, gender, age, money) values (98, 'Tobie', 'China', 'Male', 85, 48088);
insert into People (id, first_name, country, gender, age, money) values (99, 'Rod', 'Thailand', 'Male', 29, 35215);
insert into People (id, first_name, country, gender, age, money) values (100, 'Joellen', 'Brazil', 'Female', 72, 30315);
insert into People (id, first_name, country, gender, age, money) values (101, 'Lemuel', 'Portugal', 'Male', 57, 53588);
insert into People (id, first_name, country, gender, age, money) values (102, 'Florinda', 'Peru', 'Female', 46, 2212);
insert into People (id, first_name, country, gender, age, money) values (103, 'Cam', 'Poland', 'Male', 21, 49028);
insert into People (id, first_name, country, gender, age, money) values (104, 'Arabel', 'China', 'Female', 22, 66240);
insert into People (id, first_name, country, gender, age, money) values (105, 'Reggie', 'Indonesia', 'Male', 43, 81498);
insert into People (id, first_name, country, gender, age, money) values (106, 'Davie', 'China', 'Male', 77, 46014);
insert into People (id, first_name, country, gender, age, money) values (107, 'Pen', 'Indonesia', 'Male', 5, 57721);
insert into People (id, first_name, country, gender, age, money) values (108, 'Skylar', 'United States', 'Polygender', 83, 82446);
insert into People (id, first_name, country, gender, age, money) values (109, 'Ham', 'Philippines', 'Male', 8, 233);
insert into People (id, first_name, country, gender, age, money) values (110, 'Mart', 'Brazil', 'Male', 53, 18488);
insert into People (id, first_name, country, gender, age, money) values (111, 'Rosita', 'France', 'Female', 49, 44812);
insert into People (id, first_name, country, gender, age, money) values (112, 'Babette', 'Mexico', 'Female', 80, 25483);
insert into People (id, first_name, country, gender, age, money) values (113, 'Ezmeralda', 'Czech Republic', 'Female', 53, 30919);
insert into People (id, first_name, country, gender, age, money) values (114, 'Sandro', 'United Kingdom', 'Male', 6, 61313);
insert into People (id, first_name, country, gender, age, money) values (115, 'Dorine', 'Croatia', 'Female', 12, 81911);
insert into People (id, first_name, country, gender, age, money) values (116, 'Powell', 'Mexico', 'Male', 24, 99616);
insert into People (id, first_name, country, gender, age, money) values (117, 'Elsa', 'Russia', 'Female', 1, 505);
insert into People (id, first_name, country, gender, age, money) values (118, 'Salvatore', 'Indonesia', 'Male', 59, 73534);
insert into People (id, first_name, country, gender, age, money) values (119, 'Christoffer', 'China', 'Male', 17, 60569);
insert into People (id, first_name, country, gender, age, money) values (120, 'Callean', 'United Kingdom', 'Polygender', 9, 41131);
insert into People (id, first_name, country, gender, age, money) values (121, 'Lem', 'Afghanistan', 'Male', 17, 29902);
insert into People (id, first_name, country, gender, age, money) values (122, 'Tyne', 'China', 'Female', 31, 45893);
insert into People (id, first_name, country, gender, age, money) values (123, 'Akim', 'Indonesia', 'Male', 80, 33237);
insert into People (id, first_name, country, gender, age, money) values (124, 'Karla', 'Jordan', 'Female', 10, 5650);
insert into People (id, first_name, country, gender, age, money) values (125, 'Maia', 'Aland Islands', 'Female', 66, 36201);
insert into People (id, first_name, country, gender, age, money) values (126, 'Adda', 'Portugal', 'Female', 68, 71361);
insert into People (id, first_name, country, gender, age, money) values (127, 'Sheeree', 'Portugal', 'Female', 51, 19411);
insert into People (id, first_name, country, gender, age, money) values (128, 'Thurston', 'Portugal', 'Male', 47, 78786);
insert into People (id, first_name, country, gender, age, money) values (129, 'Cathe', 'Greece', 'Female', 99, 16115);
insert into People (id, first_name, country, gender, age, money) values (130, 'Brewster', 'Indonesia', 'Male', 52, 704);
insert into People (id, first_name, country, gender, age, money) values (131, 'Tybalt', 'Slovenia', 'Male', 27, 99950);
insert into People (id, first_name, country, gender, age, money) values (132, 'Fianna', 'Brazil', 'Female', 97, 86638);
insert into People (id, first_name, country, gender, age, money) values (133, 'Lizzie', 'Russia', 'Female', 85, 53607);
insert into People (id, first_name, country, gender, age, money) values (134, 'Dylan', 'Indonesia', 'Male', 56, 93619);
insert into People (id, first_name, country, gender, age, money) values (135, 'Kendrick', 'Indonesia', 'Male', 100, 48370);
insert into People (id, first_name, country, gender, age, money) values (136, 'Marget', 'Finland', 'Agender', 17, 51591);
insert into People (id, first_name, country, gender, age, money) values (137, 'Emera', 'China', 'Female', 97, 47564);
insert into People (id, first_name, country, gender, age, money) values (138, 'Grace', 'Czech Republic', 'Male', 63, 10495);
insert into People (id, first_name, country, gender, age, money) values (139, 'Aimil', 'Portugal', 'Female', 21, 79350);
insert into People (id, first_name, country, gender, age, money) values (140, 'Vin', 'Palestinian Territory', 'Male', 27, 80785);
insert into People (id, first_name, country, gender, age, money) values (141, 'Ali', 'Guatemala', 'Male', 27, 27591);
insert into People (id, first_name, country, gender, age, money) values (142, 'Fairfax', 'Poland', 'Male', 36, 99698);
insert into People (id, first_name, country, gender, age, money) values (143, 'Martynne', 'China', 'Female', 8, 88332);
insert into People (id, first_name, country, gender, age, money) values (144, 'Ema', 'Portugal', 'Female', 98, 57314);
insert into People (id, first_name, country, gender, age, money) values (145, 'Ronna', 'Central African Republic', 'Female', 60, 37892);
insert into People (id, first_name, country, gender, age, money) values (146, 'Ruddy', 'Indonesia', 'Genderfluid', 71, 30199);
insert into People (id, first_name, country, gender, age, money) values (147, 'Jacintha', 'United States', 'Female', 16, 81986);
insert into People (id, first_name, country, gender, age, money) values (148, 'Benton', 'Afghanistan', 'Male', 54, 20229);
insert into People (id, first_name, country, gender, age, money) values (149, 'Claire', 'Thailand', 'Male', 62, 40652);
insert into People (id, first_name, country, gender, age, money) values (150, 'Catha', 'Russia', 'Genderqueer', 1, 33663);
insert into People (id, first_name, country, gender, age, money) values (151, 'Allin', 'Nepal', 'Male', 10, 51992);
insert into People (id, first_name, country, gender, age, money) values (152, 'Allin', 'China', 'Male', 33, 9091);
insert into People (id, first_name, country, gender, age, money) values (153, 'Jelene', 'Canada', 'Female', 1, 48285);
insert into People (id, first_name, country, gender, age, money) values (154, 'Locke', 'Canada', 'Male', 46, 62243);
insert into People (id, first_name, country, gender, age, money) values (155, 'Fritz', 'Afghanistan', 'Male', 31, 4641);
insert into People (id, first_name, country, gender, age, money) values (156, 'Cris', 'Portugal', 'Male', 41, 52044);
insert into People (id, first_name, country, gender, age, money) values (157, 'Rolf', 'Brazil', 'Male', 9, 15315);
insert into People (id, first_name, country, gender, age, money) values (158, 'Quentin', 'Portugal', 'Female', 67, 40379);
insert into People (id, first_name, country, gender, age, money) values (159, 'Dierdre', 'Vietnam', 'Female', 42, 74798);
insert into People (id, first_name, country, gender, age, money) values (160, 'Rania', 'Nigeria', 'Female', 42, 46308);
insert into People (id, first_name, country, gender, age, money) values (161, 'Elmira', 'Russia', 'Genderfluid', 94, 69784);
insert into People (id, first_name, country, gender, age, money) values (162, 'Rozamond', 'Ireland', 'Agender', 2, 68898);
insert into People (id, first_name, country, gender, age, money) values (163, 'Lauritz', 'Indonesia', 'Male', 95, 46217);
insert into People (id, first_name, country, gender, age, money) values (164, 'Lanna', 'France', 'Female', 23, 30176);
insert into People (id, first_name, country, gender, age, money) values (165, 'Sherline', 'Venezuela', 'Female', 42, 2437);
insert into People (id, first_name, country, gender, age, money) values (166, 'Kellby', 'North Korea', 'Male', 97, 83778);
insert into People (id, first_name, country, gender, age, money) values (167, 'Rolando', 'China', 'Male', 10, 47609);
insert into People (id, first_name, country, gender, age, money) values (168, 'Celle', 'Syria', 'Female', 93, 33983);
insert into People (id, first_name, country, gender, age, money) values (169, 'Bram', 'Philippines', 'Male', 33, 55210);
insert into People (id, first_name, country, gender, age, money) values (170, 'Bert', 'Indonesia', 'Male', 9, 97720);
insert into People (id, first_name, country, gender, age, money) values (171, 'Sheba', 'Belarus', 'Female', 67, 57807);
insert into People (id, first_name, country, gender, age, money) values (172, 'Madelon', 'Peru', 'Female', 91, 27633);
insert into People (id, first_name, country, gender, age, money) values (173, 'Breanne', 'Philippines', 'Female', 89, 63134);
insert into People (id, first_name, country, gender, age, money) values (174, 'Bil', 'Guatemala', 'Male', 84, 27972);
insert into People (id, first_name, country, gender, age, money) values (175, 'Lucky', 'China', 'Female', 55, 36751);
insert into People (id, first_name, country, gender, age, money) values (176, 'Blaine', 'China', 'Male', 42, 36204);
insert into People (id, first_name, country, gender, age, money) values (177, 'Benson', 'Singapore', 'Genderqueer', 38, 72168);
insert into People (id, first_name, country, gender, age, money) values (178, 'Zelig', 'Syria', 'Male', 20, 44015);
insert into People (id, first_name, country, gender, age, money) values (179, 'Derron', 'Indonesia', 'Male', 7, 98104);
insert into People (id, first_name, country, gender, age, money) values (180, 'Lanie', 'Yemen', 'Male', 22, 89225);
insert into People (id, first_name, country, gender, age, money) values (181, 'Alberto', 'Colombia', 'Male', 54, 73745);
insert into People (id, first_name, country, gender, age, money) values (182, 'Dominga', 'Poland', 'Agender', 10, 65061);
insert into People (id, first_name, country, gender, age, money) values (183, 'Ileane', 'France', 'Female', 94, 76882);
insert into People (id, first_name, country, gender, age, money) values (184, 'Peter', 'Portugal', 'Male', 79, 43666);
insert into People (id, first_name, country, gender, age, money) values (185, 'Jessa', 'Croatia', 'Female', 56, 67379);
insert into People (id, first_name, country, gender, age, money) values (186, 'Hans', 'United States', 'Male', 9, 17744);
insert into People (id, first_name, country, gender, age, money) values (187, 'Nonnah', 'Greece', 'Female', 31, 37693);
insert into People (id, first_name, country, gender, age, money) values (188, 'Karine', 'China', 'Female', 53, 76079);
insert into People (id, first_name, country, gender, age, money) values (189, 'Palm', 'Malta', 'Male', 93, 87667);
insert into People (id, first_name, country, gender, age, money) values (190, 'Marsh', 'Portugal', 'Male', 4, 16266);
insert into People (id, first_name, country, gender, age, money) values (191, 'Estevan', 'Brazil', 'Male', 89, 99887);
insert into People (id, first_name, country, gender, age, money) values (192, 'Dev', 'Netherlands', 'Genderqueer', 11, 62293);
insert into People (id, first_name, country, gender, age, money) values (193, 'Kippy', 'Philippines', 'Male', 88, 42287);
insert into People (id, first_name, country, gender, age, money) values (194, 'Marleen', 'China', 'Female', 45, 68026);
insert into People (id, first_name, country, gender, age, money) values (195, 'Homer', 'China', 'Male', 87, 5187);
insert into People (id, first_name, country, gender, age, money) values (196, 'Lani', 'China', 'Female', 20, 60366);
insert into People (id, first_name, country, gender, age, money) values (197, 'Lilian', 'China', 'Bigender', 37, 88915);
insert into People (id, first_name, country, gender, age, money) values (198, 'Dael', 'Portugal', 'Male', 40, 47684);
insert into People (id, first_name, country, gender, age, money) values (199, 'Denna', 'China', 'Female', 82, 5214);
insert into People (id, first_name, country, gender, age, money) values (200, 'Rosalie', 'Philippines', 'Female', 30, 26526);
insert into People (id, first_name, country, gender, age, money) values (201, 'Perkin', 'Indonesia', 'Male', 43, 23425);
insert into People (id, first_name, country, gender, age, money) values (202, 'Ragnar', 'Colombia', 'Male', 95, 61553);
insert into People (id, first_name, country, gender, age, money) values (203, 'Mercie', 'France', 'Female', 56, 37674);
insert into People (id, first_name, country, gender, age, money) values (204, 'Dorelle', 'Indonesia', 'Female', 90, 55290);
insert into People (id, first_name, country, gender, age, money) values (205, 'Umeko', 'Russia', 'Female', 42, 79581);
insert into People (id, first_name, country, gender, age, money) values (206, 'Aggie', 'Malaysia', 'Genderqueer', 23, 66693);
insert into People (id, first_name, country, gender, age, money) values (207, 'Vivyanne', 'Indonesia', 'Female', 60, 97086);
insert into People (id, first_name, country, gender, age, money) values (208, 'Desmund', 'China', 'Male', 81, 62931);
insert into People (id, first_name, country, gender, age, money) values (209, 'Victoir', 'Panama', 'Male', 60, 29623);
insert into People (id, first_name, country, gender, age, money) values (210, 'Karla', 'Indonesia', 'Agender', 31, 14840);
insert into People (id, first_name, country, gender, age, money) values (211, 'Teador', 'Honduras', 'Male', 2, 64917);
insert into People (id, first_name, country, gender, age, money) values (212, 'Melba', 'France', 'Female', 92, 32029);
insert into People (id, first_name, country, gender, age, money) values (213, 'Leo', 'United States', 'Non-binary', 45, 39567);
insert into People (id, first_name, country, gender, age, money) values (214, 'Grethel', 'China', 'Female', 66, 24046);
insert into People (id, first_name, country, gender, age, money) values (215, 'Davidson', 'China', 'Male', 22, 64442);
insert into People (id, first_name, country, gender, age, money) values (216, 'Uri', 'Argentina', 'Male', 81, 88017);
insert into People (id, first_name, country, gender, age, money) values (217, 'Land', 'China', 'Male', 15, 94116);
insert into People (id, first_name, country, gender, age, money) values (218, 'Willi', 'Zambia', 'Female', 50, 23447);
insert into People (id, first_name, country, gender, age, money) values (219, 'Joanie', 'China', 'Bigender', 53, 41540);
insert into People (id, first_name, country, gender, age, money) values (220, 'Jehanna', 'Indonesia', 'Female', 43, 22292);
insert into People (id, first_name, country, gender, age, money) values (221, 'Vernen', 'China', 'Male', 34, 99475);
insert into People (id, first_name, country, gender, age, money) values (222, 'Alexine', 'United Kingdom', 'Female', 94, 76598);
insert into People (id, first_name, country, gender, age, money) values (223, 'Quentin', 'China', 'Female', 56, 79469);
insert into People (id, first_name, country, gender, age, money) values (224, 'Jermaine', 'Belarus', 'Male', 95, 44526);
insert into People (id, first_name, country, gender, age, money) values (225, 'Benton', 'Indonesia', 'Male', 3, 95305);
insert into People (id, first_name, country, gender, age, money) values (226, 'Galvan', 'Philippines', 'Male', 82, 8682);
insert into People (id, first_name, country, gender, age, money) values (227, 'Hatty', 'Japan', 'Female', 84, 47085);
insert into People (id, first_name, country, gender, age, money) values (228, 'Robinett', 'Honduras', 'Female', 52, 89567);
insert into People (id, first_name, country, gender, age, money) values (229, 'Kelci', 'Bolivia', 'Female', 45, 97509);
insert into People (id, first_name, country, gender, age, money) values (230, 'Florella', 'China', 'Female', 99, 56660);
insert into People (id, first_name, country, gender, age, money) values (231, 'Simeon', 'Costa Rica', 'Male', 71, 67308);
insert into People (id, first_name, country, gender, age, money) values (232, 'Denni', 'Indonesia', 'Female', 78, 13647);
insert into People (id, first_name, country, gender, age, money) values (233, 'Giff', 'Argentina', 'Male', 64, 40828);
insert into People (id, first_name, country, gender, age, money) values (234, 'Oliviero', 'Azerbaijan', 'Male', 42, 49894);
insert into People (id, first_name, country, gender, age, money) values (235, 'Rikki', 'Indonesia', 'Female', 23, 17275);
insert into People (id, first_name, country, gender, age, money) values (236, 'Pooh', 'Indonesia', 'Female', 52, 59402);
insert into People (id, first_name, country, gender, age, money) values (237, 'Leandra', 'South Africa', 'Female', 98, 15179);
insert into People (id, first_name, country, gender, age, money) values (238, 'Marshall', 'Portugal', 'Male', 42, 43652);
insert into People (id, first_name, country, gender, age, money) values (239, 'Caryl', 'Brazil', 'Female', 70, 14729);
insert into People (id, first_name, country, gender, age, money) values (240, 'Garnette', 'Kuwait', 'Female', 35, 94619);
insert into People (id, first_name, country, gender, age, money) values (241, 'Imogene', 'Brazil', 'Polygender', 81, 58507);
insert into People (id, first_name, country, gender, age, money) values (242, 'Kittie', 'Honduras', 'Female', 70, 80223);
insert into People (id, first_name, country, gender, age, money) values (243, 'Guilbert', 'Japan', 'Male', 62, 46195);
insert into People (id, first_name, country, gender, age, money) values (244, 'Eyde', 'China', 'Female', 99, 78272);
insert into People (id, first_name, country, gender, age, money) values (245, 'Ailyn', 'Indonesia', 'Female', 76, 38784);
insert into People (id, first_name, country, gender, age, money) values (246, 'Oralla', 'Russia', 'Female', 85, 17563);
insert into People (id, first_name, country, gender, age, money) values (247, 'Alwin', 'North Korea', 'Bigender', 100, 52183);
insert into People (id, first_name, country, gender, age, money) values (248, 'Granger', 'France', 'Male', 91, 85732);
insert into People (id, first_name, country, gender, age, money) values (249, 'Farah', 'Brazil', 'Female', 75, 64613);
insert into People (id, first_name, country, gender, age, money) values (250, 'Silvester', 'Croatia', 'Male', 80, 32120);
insert into People (id, first_name, country, gender, age, money) values (251, 'Elena', 'Botswana', 'Female', 28, 13452);
insert into People (id, first_name, country, gender, age, money) values (252, 'Kane', 'South Africa', 'Male', 18, 26978);
insert into People (id, first_name, country, gender, age, money) values (253, 'Dore', 'China', 'Female', 87, 19013);
insert into People (id, first_name, country, gender, age, money) values (254, 'Peri', 'Poland', 'Female', 32, 50953);
insert into People (id, first_name, country, gender, age, money) values (255, 'Carma', 'Equatorial Guinea', 'Female', 70, 7706);
insert into People (id, first_name, country, gender, age, money) values (256, 'Kristopher', 'France', 'Male', 53, 76663);
insert into People (id, first_name, country, gender, age, money) values (257, 'Shauna', 'Papua New Guinea', 'Female', 81, 82100);
insert into People (id, first_name, country, gender, age, money) values (258, 'Ally', 'Finland', 'Female', 49, 95743);
insert into People (id, first_name, country, gender, age, money) values (259, 'Wrennie', 'Cuba', 'Female', 57, 83422);
insert into People (id, first_name, country, gender, age, money) values (260, 'Mattheus', 'Portugal', 'Bigender', 57, 77064);
insert into People (id, first_name, country, gender, age, money) values (261, 'Car', 'Sri Lanka', 'Male', 49, 91330);
insert into People (id, first_name, country, gender, age, money) values (262, 'Gustavo', 'Poland', 'Male', 64, 18005);
insert into People (id, first_name, country, gender, age, money) values (263, 'Marquita', 'China', 'Non-binary', 67, 52274);
insert into People (id, first_name, country, gender, age, money) values (264, 'Godwin', 'China', 'Male', 40, 81772);
insert into People (id, first_name, country, gender, age, money) values (265, 'Opalina', 'Russia', 'Female', 60, 52667);
insert into People (id, first_name, country, gender, age, money) values (266, 'Enrique', 'Indonesia', 'Non-binary', 2, 44285);
insert into People (id, first_name, country, gender, age, money) values (267, 'Zsazsa', 'China', 'Female', 55, 19424);
insert into People (id, first_name, country, gender, age, money) values (268, 'Gardy', 'France', 'Male', 31, 58156);
insert into People (id, first_name, country, gender, age, money) values (269, 'Elsie', 'China', 'Female', 80, 47263);
insert into People (id, first_name, country, gender, age, money) values (270, 'Jackquelin', 'Cuba', 'Female', 6, 17952);
insert into People (id, first_name, country, gender, age, money) values (271, 'Randolph', 'Guatemala', 'Male', 63, 52447);
insert into People (id, first_name, country, gender, age, money) values (272, 'Morgan', 'Madagascar', 'Female', 21, 65536);
insert into People (id, first_name, country, gender, age, money) values (273, 'Marylou', 'Indonesia', 'Female', 48, 14397);
insert into People (id, first_name, country, gender, age, money) values (274, 'Hetty', 'Portugal', 'Female', 76, 48714);
insert into People (id, first_name, country, gender, age, money) values (275, 'Lion', 'Egypt', 'Male', 6, 600);
insert into People (id, first_name, country, gender, age, money) values (276, 'Jacob', 'Uzbekistan', 'Male', 21, 23723);
insert into People (id, first_name, country, gender, age, money) values (277, 'Gusty', 'China', 'Female', 52, 40105);
insert into People (id, first_name, country, gender, age, money) values (278, 'Carolan', 'Sweden', 'Bigender', 47, 1313);
insert into People (id, first_name, country, gender, age, money) values (279, 'Galvan', 'Brazil', 'Male', 87, 54903);
insert into People (id, first_name, country, gender, age, money) values (280, 'Fey', 'Russia', 'Female', 81, 75385);
insert into People (id, first_name, country, gender, age, money) values (281, 'Rozella', 'Argentina', 'Female', 27, 50633);
insert into People (id, first_name, country, gender, age, money) values (282, 'Aloin', 'China', 'Male', 12, 43635);
insert into People (id, first_name, country, gender, age, money) values (283, 'Jaime', 'Russia', 'Male', 30, 47216);
insert into People (id, first_name, country, gender, age, money) values (284, 'Kane', 'Portugal', 'Male', 55, 48104);
insert into People (id, first_name, country, gender, age, money) values (285, 'Debera', 'El Salvador', 'Female', 53, 43005);
insert into People (id, first_name, country, gender, age, money) values (286, 'Janina', 'Russia', 'Female', 65, 2951);
insert into People (id, first_name, country, gender, age, money) values (287, 'Honey', 'Netherlands', 'Female', 50, 25505);
insert into People (id, first_name, country, gender, age, money) values (288, 'Amargo', 'Morocco', 'Female', 47, 23098);
insert into People (id, first_name, country, gender, age, money) values (289, 'Felizio', 'Bulgaria', 'Male', 72, 71698);
insert into People (id, first_name, country, gender, age, money) values (290, 'Peyton', 'Peru', 'Male', 19, 9886);
insert into People (id, first_name, country, gender, age, money) values (291, 'Camey', 'Russia', 'Male', 52, 74471);
insert into People (id, first_name, country, gender, age, money) values (292, 'Chester', 'Bermuda', 'Male', 10, 98673);
insert into People (id, first_name, country, gender, age, money) values (293, 'Estevan', 'Netherlands', 'Male', 82, 43914);
insert into People (id, first_name, country, gender, age, money) values (294, 'Ava', 'Thailand', 'Female', 49, 84349);
insert into People (id, first_name, country, gender, age, money) values (295, 'Gianna', 'Indonesia', 'Female', 17, 63575);
insert into People (id, first_name, country, gender, age, money) values (296, 'Worden', 'Nicaragua', 'Male', 59, 49512);
insert into People (id, first_name, country, gender, age, money) values (297, 'Cammi', 'Indonesia', 'Agender', 85, 40940);
insert into People (id, first_name, country, gender, age, money) values (298, 'Giacinta', 'Brazil', 'Female', 38, 16568);
insert into People (id, first_name, country, gender, age, money) values (299, 'Gilburt', 'Indonesia', 'Male', 31, 86149);
insert into People (id, first_name, country, gender, age, money) values (300, 'Lorenzo', 'Thailand', 'Male', 42, 83722);
